#!/bin/bash
set -euo pipefail

runscript() { deps 
  yarn script "$@"
}

deps() {
    yarn install
}


if declare -f "${1}" >/dev/null; then
  nix-shell --version || curl -L https://nixos.org/nix/install | sh; . ~/.nix-profile/etc/profile.d/nix.sh
  sub="${1}"; shift
  if echo ${shell} | grep nix; then
    "$sub" "$@" # invoke our named function w/ all remaining arguments
  else
    nix-shell --run "$(printf "%q " command "$0" "$sub" "$@")"
  fi
else
  PROGNAME=$(basename $0); echo "Subcommand '$1' not recognized. Run './${PROGNAME} help' for docs." >&2; exit 1
fi